### ISSUE TITLE
Not all syntax highlighting matches that of Atom's one dark theme.

### ISSUE THREAD

**Issue by BurningSmile** [joshdick/onedark.vim#106]
- [x ] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [ x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

Terminal emulator(s) and their version(s) used, if applicable: 
urxvt-unicode-256 tmux with 256 color support enabled and setup

### Output From `vim --version`
https://hastebin.burningsmile.tech/tonuxajeja

### Issue Description

Hello!

I happened to notice that not everything in your syntax matches that of one dark's color scheme. Take this js snippet for example. 
https://i.imgur.com/kofwUD2.png

This can also be seen with things such as markdown.
https://i.imgur.com/ozymCVg.png

Code snippet I used for testing.
https://hastebin.burningsmile.tech/nonikacota.xml

**Comment by joshdick** [comment]
It's not possible to get a perfect 1:1 match between the Vim theme and Atom's syntax highlighting because Vim and Atom use different approaches for syntax highlighting. The Vim theme also has several differences from the Atom theme that were added on purpose, to enhance readability inside Vim.

That said, you will have better syntax highlighting results with `onedark.vim` if you use it in combination with [vim-polyglot](https://github.com/sheerun/vim-polyglot), which provides enhanced syntax highlighting over stock Vim for a whole bunch of languages.

Given the explanation above, I'm going to close this issue, but feel free to keep the conversation going here!

**Comment by simonsmith** [comment]
@BurningSmile I have a feeling your terminal colours might not be set correctly. Here is that snippet with my Vim and Atom:

![screen shot 2017-08-06 at 23 28 49](https://user-images.githubusercontent.com/360703/29007624-1afcf648-7aff-11e7-8ed3-3032b99a74eb.png)

**Comment by joshdick** [comment]
@simonsmith Appears to be correct, that's what I get for trying to look at the screenshots on mobile! 🙃

**Comment by john-cj** [comment]
@simonsmith First of all "hallo!" and thanks for this amazing theme.

> It's not possible to get a perfect 1:1 match between the Vim theme and Atom's syntax highlighting because Vim and Atom use different approaches for syntax highlighting.

Here is the test file for Asciidoctor syntax:

![atomvim](https://user-images.githubusercontent.com/18004961/52524065-c18f4d00-2ca9-11e9-866d-814d988c0a38.png)

As you can see, the colors are almost the same, but they are used for completely different elements. For example, green color is used for code in Atom, whereas it is used for headings in Vim (and so on).

Is it that difference that you talked about?

**Comment by john-cj** [comment]
@joshdick First of all "hallo!" and thanks for this amazing theme.

> It's not possible to get a perfect 1:1 match between the Vim theme and Atom's syntax highlighting because Vim and Atom use different approaches for syntax highlighting.

Here is the test file for Asciidoctor syntax:

![atomvim](https://user-images.githubusercontent.com/18004961/52524246-1207aa00-2cac-11e9-8e77-769e4e46a57c.png)

As you can see, the colors are almost the same, but they are used for completely different elements. For example, green color is used for code in Atom, whereas it is used for headings in Vim (and so on).

Is it that difference that you talked about?

**Comment by joshdick** [comment]
@john-cj Yes, that’s exactly right, that is indeed the difference I was describing.

**Comment by raiguard** [comment]
Sorry to gravedig, but the differences between the Atom and vim implementations is quite stark, and the vim changes are much less readable for me.

Have a look:

![image](https://user-images.githubusercontent.com/3515394/103143677-a4ff3100-46d8-11eb-8199-6539ab63a533.png)

(ignore the darker background color, that's an intentional change by me)

There are many differences here, many of which I don't get:
- Top-level keywords are colored red while others purple (which is the correct color)
- Function parameters are colored red as well, when they should be white to match other variables
- The colors of types and structs/tuples are switched around in some cases

The first two are the biggest things for me - it makes it so that function parameters are colored the same as top-level keywords, which is just confusing to me. I'm using `nvim-treesitter`, so the parsing engine is the same across both programs. Can I somehow fix it so it looks more like the Atom version?
