### ISSUE TITLE
Tab highlighting 

### ISSUE THREAD

**Issue by gopz** [joshdick/onedark.vim#12]
Is there anyway to highlight whatever tab is open within vim?

What it looks like now: 
<img width="1240" alt="screenshot 2016-02-22 11 51 52" src="https://cloud.githubusercontent.com/assets/3451290/13225406/be8d6bb4-d95a-11e5-97fc-646baa78f1e0.png">

Ideally I could see something like this (with your color scheme ofc): 
<img width="1240" alt="screenshot 2016-02-22 11 53 51" src="https://cloud.githubusercontent.com/assets/3451290/13225465/f82da7b2-d95a-11e5-801e-54d28bfc6f12.png">

**Comment by joshdick** [comment]
Here are two possibilities ("No Name" is selected in both cases):

<img width="153" alt="bold" src="https://cloud.githubusercontent.com/assets/424691/13229577/b57c7d34-d96f-11e5-8e11-0a032308ec7c.png">

<img width="158" alt="nonbold" src="https://cloud.githubusercontent.com/assets/424691/13229576/b57c8784-d96f-11e5-8ff0-14bd0d5e741d.png">

What worries me about using the bold font (first example) is that users may have their terminal emulator configured to show ANSI "bright" colors when bold fonts are used instead of actually bolding the font, which would cause the selected tab to also appear grey when using 16 color mode.

What do you think?

**Comment by kyeb** [comment]
I agree that the bold font might not be a good option, but my default Vim color scheme makes it clear which tab is selected by setting it to the same color as the background, and "highlighting" all the un-selected tabs. 
I would like something like your second example, but having the highlighting reversed.

Is this something that seems reasonable, in terms of UI/UX and to implement?

**Comment by joshdick** [comment]
@kyeb 

This is totally personal preference, but I don't want to change this since I'm not a fan of the idea of a light-colored bar of unfocused tabs.

That said, you should be able to [override](https://github.com/joshdick/onedark.vim#onedarkset_highlight) onedark.vim's highlights for `TabLine`/`TabLineFill`/`TabLineSel` in your own configuration to match what you're after.

**Comment by kyeb** [comment]
That's true, a light-colored bar at the top doesn't seem perfect, now that I think about it. 

I'll keep messing around with the colors and see if I can come up with something I like, but thanks for the help! The `TabLine`/`TabLineFill`/`TabLineSel` groups were exactly what I was looking for.

**Comment by joshdick** [comment]
@kyeb You're welcome!
