### ISSUE TITLE
Booleans and Numbers have the same color in Python.

### ISSUE THREAD

**Issue by TerminatorP** [joshdick/onedark.vim#127]
Syntax Highlighting for Boolean values and Number values are same in python. Please fix this issue.
I am using Gvim 8.1.22
![screenshot from 2018-07-17 23-03-17](https://user-images.githubusercontent.com/30633774/42834061-ada467f8-8a15-11e8-88ee-aa99bc61af6b.png)

**Comment by joshdick** [comment]
Atom's own One Dark theme treats this the same way, so I don't think this is a bug.

You can still accomplish the behavior you want by adding the following above the `colorscheme onedark` line in your `.vimrc` and customizing it to your needs:

```vim
if (has("autocmd"))
  augroup colorset
    autocmd!
    let s:green = { "gui": "#98C379", "cterm": "114", "cterm16": "2" }
    autocmd ColorScheme * call onedark#set_highlight("pythonBoolean", { "fg": s:green })
  augroup END
endif
```

For the example you gave, if you install [vim-polyglot](https://github.com/sheerun/vim-polyglot), you can use `pythonFloat` (or `pythonNumber` to cover all numbers) instead of `pythonBoolean`, and you can find colors other than green in `autoload/onedark.vim`.
