### ISSUE TITLE
issues with color

### ISSUE THREAD

**Issue by GMHDBJD** [joshdick/onedark.vim#144]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

Terminal emulator(s) and their version(s) used, if applicable: `terminator`

### Output From `vim --version`

```
8.1
```

### Issue Description

Write your issue description here.

why my vim color theme different with standard?
![screenshot from 2019-01-14 08-38-15](https://user-images.githubusercontent.com/35025882/51126470-0f628380-17d8-11e9-953d-eff4803cc8ea.png)

**Comment by joshdick** [comment]
Do you have `let g:onedark_termcolors` set? If so, that's probably why. To get the colors to look like those in the screenshot, you need to do ONE of the following:
* [Preferred] Assuming your terminal supports 24-bit color, you should configure Vim to use 24-bit color as shown in the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation). You appear to be using xterm, which [may not correctly support 24-bit color](https://gist.github.com/XVilka/8346728#parsing-ansi-colour-sequences-but-approximating-them-to-256-palette), so you might have better luck switching to a terminal emulator that does (see higher up on the previously linked page for a list.)
* [Workaround] If you don't want to switch terminal emulators, update your `.vimrc`. to include `let g:onedark_termcolors=16`, and configure your terminal emulator to use [onedark.vim's 16-color palette](https://github.com/joshdick/onedark.vim/blob/master/term/One%20Dark.Xresources).

**Comment by GMHDBJD** [comment]
Does this mean than my terminal not supports 24-bit color?
![screenshot from 2019-01-14 09-40-01](https://user-images.githubusercontent.com/35025882/51129890-84d25200-17e0-11e9-971b-f64145590583.png)

**Comment by joshdick** [comment]
According to https://gist.github.com/XVilka/8346728#parsing-ansi-colour-sequences-but-approximating-them-to-256-palette, xterm understands 24-bit color sequences but doesn't actually show the correct colors, which might be causing what you're seeing.

You should try a different terminal emulator to see if there's any difference. Since you're using GNOME, the easiest one for you to try would be gnome-terminal, which should correctly support 24-bit color.

**Comment by GMHDBJD** [comment]
I'm now using gnome terminal, but it still went wrong.
here is my .vimrc
![screenshot from 2019-01-14 19-32-31](https://user-images.githubusercontent.com/35025882/51157102-39955f00-1833-11e9-9b70-e4d62e7507ec.png)

**Comment by joshdick** [comment]
The colors look correct in your screenshot; I even color-sampled the background of the `.vimrc` in the top left corner of your screenshot and it is an exact match for onedark.vim's 24-bit green (`#98C379`):

<img width="911" alt="colortest" src="https://user-images.githubusercontent.com/424691/51159591-f8fc0c80-1857-11e9-989b-a7ad2f42be25.png">

If you are wondering why things look slightly darker overall in your screenshot than the one in the onedark.vim README, I think it has to do with your font and/or font smoothing settings. Your font's characters are thinner overall than the one used in the README screenshot, which makes them look darker, and the edges are blurred more (smoothing), which also makes them look darker.

I don't think there's any debugging left to do here since everything seems to be working correctly, so I'm going to close this issue, but feel free to keep the conversation going if you want.
