### ISSUE TITLE
change background for GVIM

### ISSUE THREAD

**Issue by generic11** [joshdick/onedark.vim#167]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

GVIM WINDOWS 10

### Output From `vim --version`

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan  6 2019 23:01:57)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-700
```

### Issue Description

Excellent colorscheme! I wuld like to change the background to be less grey and more black when using GVIM.
The following code works fine in terminal, but how would I change it for GVIM?
(I've tried removing the && portion in the condition, but no luck.)
I am using set termguicolors (if that matters.)

if (has("autocmd") && !has("gui_running"))
  augroup colors
    autocmd!
      let s:background = { "gui": "#000000", "cterm": "235", "cterm16": "0" }
      autocmd ColorScheme * call onedark#set_highlight("Normal", { "bg": s:background }) "No `fg` setting
      augroup END
endif

**Comment by joshdick** [comment]
Two things that should get it working:

1) The first line should look like `if (has("autocmd") && has("gui_running"))` (without the exclamation point); `has("gui_running")` should detect the gvim environment.

2) This code needs to appear **before** the `colorscheme onedark` line in your `.vimrc`. Changing the colorscheme is what triggers `autocmd ColorScheme`, so if you define the `autocmd` after `colorscheme onedark`, it won't run.

I'm going to close this issue since I'm confident that making these two changes to your configuration will solve it, but feel free to keep the conversation going either way!
