### ISSUE TITLE
Decent colours for vimdiff

### ISSUE THREAD

**Issue by dagadbm** [joshdick/onedark.vim#210]
Hey Josh!

Would you be willing to add / fix the colouring scheme when we are using vim diff? it is kind of atrocious with the underlines when there is a change and selecting the entire text with the green/red background.

Is this possible to be removed?
For an example just have two open windows on vim with some text and do :windo diffthis.

have any idea on how we could make the vim diff actually pretty?

**Comment by joshdick** [comment]
There are a few prior requests and some discussion around the vimdiff styling:

#59 
#84
#126 

Given the history, do you have specific ideas or suggestions for improvements, since "make the vim diff actually pretty" isn't very actionable? Or even better, could you open up a pull request that implements the changes you're envisioning? (The relevant highlight groups would be `DiffAdd`/`DiffChange`/`DiffDelete`/`DiffText`; see https://github.com/joshdick/onedark.vim/commit/5e522e97ec31f4eb760dd56a6bc1aa4b490b6130 for an example.)

**Comment by dagadbm** [comment]
Hmm maybe I have some configuration problems because my vim diff has
underlines everywhere and the colours on those MRs seem better

**Comment by joshdick** [comment]
@dagadbm Are you using an old version of `onedark.vim`? Can you post a screenshot of what you're seeing now?

**Comment by dagadbm** [comment]
[image: image.png]
[image: image.png]

Hmm.

I must have updated this in the meantime.

Is this how its supposed to look like ?

I'm not sure I like the underline but it is cleaner I guess. I guess my
only suggestionn would be to remove the underline of the changed lines
because the other ones just have a full background colour and no underline.
or just *dont* add an underline at all and just highlight the change in the
line.
It will be pretty obvious IMO with the yellow colour on the work

What do you think?

I need to get my vim config some love I have been slacking of for a while
now :(

**Comment by joshdick** [comment]
The screenshots were not properly attached when responding via e-mail, could you attach them directly using GitHub's web interface?

**Comment by dagadbm** [comment]
![image](https://user-images.githubusercontent.com/16737095/80405309-559f0180-88ba-11ea-8b02-66da78f89190.png)

**Comment by joshdick** [comment]
OK, understood. Your screenshot is indeed how it's supposed to look. 🙂 

I am going to close this issue because after some consideration, I've decided not to change the styling, and here's why:

* In vimdiff view, syntax highlighting is currently preserved, so differences need to stand out from the existing highlighting. Right now, this is done by changing the style of an entire affected line.
* For added or removed lines, entire lines are affected rather than partial lines, so changing the background color is the easiest way to draw attention to these; just changing the text color alone might be easy to miss among existing highlighting.
* For modified lines:
  * Changing the background color of the entire line doesn't make sense, since it becomes difficult to tell which parts of the line have actually changed (even when the background is inverted on the changed area, it becomes hard to tell which parts changed and and which parts stayed the same at a glance.)
   * Changing just the text color alone also doesn't make sense for the same reason as above (easy to miss.)
   * So, underlining was kept as the least-intrusive option to make it difficult to miss "this line changed" while still showing the actual changed parts via background color. For example, if the underline wasn't there, it would be easy to overlook a single-character change.

I realize this can look a bit odd when there are multiple changed lines in close proximity, but I haven't found a better compromise than the way it currently works.

**Comment by openjck** [comment]
I'm sorry to comment on an old issue, but I figured this would be better than creating a new one. I wanted to say that I agree with the previous commenters. I find the underlines unusual and would respectfully encourage you to reconsider this.

![The onedark colorscheme being used in Git's diff view, showing yellow lines under changed lines](https://user-images.githubusercontent.com/933396/160258577-a5f70365-b881-4fd6-9bc0-2e2b2f277415.png)

I'm more accustomed to and prefer the approach that the jellybeans colorscheme uses, which applies a light-colored background to changed lines and a dark-colored background to changed contents of lines.

![The jellybeans colorscheme being used in Git's diff view, showing a light blue background behind changed lines and a darker blue background behind the changed contents of lines](https://user-images.githubusercontent.com/933396/160258593-6def5c3a-2425-4698-80db-66b20a959602.png)

I know this is something of personal preference, but I think the two-tone treatment for changed lines is also more conventional. It's what [JetBrains](https://user-images.githubusercontent.com/933396/160258725-e1c769ac-e0f5-4c39-9ee7-f67815c7bac5.png), [VS Code](https://user-images.githubusercontent.com/933396/160258813-2217fa32-456e-4440-afbd-d7df1e9cfc11.png), and [Meld](https://user-images.githubusercontent.com/933396/160258715-264577a2-d791-44e8-8e8b-7dcc54bf8843.png) do, among others.

**Comment by jecaro** [comment]
I agree too. 

I love this onedark theme as much as I hate it in diff mode because of those underlines. I'm really looking at alternative because of this.

I'd appreciate a workaround if anybody has one.
