### ISSUE TITLE
onedark.vim seems to be freezing Vim when executing vim-markdown command

### ISSUE THREAD

**Issue by Melkster** [joshdick/onedark.vim#221]
I created [an issue in plasticboy/vim-markdown](https://github.com/plasticboy/vim-markdown/issues/479) where I describe freezes I'm getting with the plugin. The weird thing is that I still have to keep onedark.vim in my `init.vim` in order for the problem to persist. If I remove onedark.vim the plugin vim-markdown works fine. Could this problem be caused by onedark.vim?

**Comment by brokenax3** [comment]
Same here. When I comment out onedark.vim from the list of plugins, the `ge` and `gx` commands work fine.

**Comment by Melkster** [comment]
[This comment](https://github.com/plasticboy/vim-markdown/issues/479#issuecomment-643609978) seems to identify the issue:

> I did some debugging and it looks like it hangs on this line: https://github.com/plasticboy/vim-markdown/blob/master/ftplugin/markdown.vim#L546
> 
> The while loop in `FindNextSyntax` waits for `'mkdURL'` syntax, but on my system it's called `'mkdUrl'` so the loop never ends.
> 
> However I don't know how to fix this properly. So I've made a fork in which all `mkdURL` strings are replaced with `mkdUrl:` https://github.com/yamnikov-oleg/vim-markdown

Is the incosistent spelling of `'mkdURL'`/`'mkdUrl'` onedark.vim's fault or is it [vim-markdown's](https://github.com/plasticboy/vim-markdown)?

**Comment by joshdick** [comment]
It looks like `vim-markdown` expects `mkdURL` rather than `mkdUrl` based  on [this search](https://github.com/plasticboy/vim-markdown/search?q=mkdUrl&unscoped_q=mkdUrl), so I've updated `onedark.vim` accordingly in #233; let me know if that has resolved the issue.

That said, it seems like this is ALSO a bug in `vim-markdown`; encountering an incorrectly-cased highlight group that it therefore seemingly shouldn't otherwise know or care about should not cause a hang.

**Comment by Melkster** [comment]
@joshdick Thanks that seems to have resolved the crashing issue!

**Comment by joshdick** [comment]
I'm glad!
