### ISSUE TITLE
<?php ?> tags not highlighted

### ISSUE THREAD

**Issue by nyuszika7h** [joshdick/onedark.vim#246]
- [x] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [x] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

* wsltty 3.3.0 
* Windows Terminal 1.5.3242.0

(Windows 10 20H2)

### Output From `vim --version`

```
NVIM v0.5.0-dev+919-g08ec36efa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az205-846

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Issue Description

`<?php ?>` tags are not highlighted, they are simply left as the default color. This appears to be an issue with this color scheme, as if I use the default vim color scheme it *is* highlighted. It happens whether I use the default PHP syntax file or vim-polyglot. True color is enabled, but it happens without too.

![Screenshot showing the issue](https://user-images.githubusercontent.com/482367/101709523-eadcb800-3a8f-11eb-9051-1379e216dc3c.png)

**Comment by joshdick** [comment]
This happens because `<?php` uses the `Delimiter` highlight group. `Delimiter` is currently unstyled/appears white because some language syntaxes make heavy use of `Delimiter` and white is the most legible/least visually distracting for those languages. In light of that, I am going to close this issue since I do not consider it to be a bug,.

Even so, to get the behavior you're after, you can override the `Delimiter` highlight group colors using the [method described in the README](https://github.com/joshdick/onedark.vim#onedarkextend_highlight):

```vim
if (has("autocmd"))
  augroup colorextend
    autocmd!
    " Override the `Delimiter` foreground color in GUI mode
    autocmd ColorScheme * call onedark#extend_highlight("Delimiter", { "fg": { "gui": "#56b6c2" } })
  augroup END
endif
```

Or a variation that would only apply to PHP:

```vim
if (has("autocmd"))
  augroup colorextend
    autocmd!
    " Override the `Delimiter` foreground color in GUI mode
    autocmd FileType php call onedark#extend_highlight("Delimiter", { "fg": { "gui": "#56b6c2" } })
  augroup END
endif
```

You can replicate one of onedark.vim's built-in colors by copying one of the values from the color reference table at the top of https://github.com/joshdick/onedark.vim/blob/master/colors/onedark.vim.

Although I'm closing this issue, feel free to keep the conversation going if needed, and thanks for using onedark.vim!
