### ISSUE TITLE
Question around what other tools are there onedark themes for?

### ISSUE THREAD

**Issue by jsatk** [joshdick/onedark.vim#248]
I love this theme. And I like my whole terminal set up to have the same theme. Previously I had tmux, vim, mutt, and iTerm all set to gruvbox. I switch to onedark and love it for vim. But unfortunately there doesn't seem to be other existing themes for it for these other aforementioned tools.

1. Are there any?
2. If not would you welcome a PR for say a iterm or mutt theme?

**Comment by joshdick** [comment]
I’m glad you love the theme!

Official themes for multiple terminal emulators are available, see https://github.com/joshdick/onedark.vim/tree/master/term . I use onedark’s colors for many CLI tools simply by using the terminal theme and then configuring those CLI tools to use 16 colors (thus inheriting the theme’s colors from the terminal.)

Because that mechanism is available and usable, I am not interested in integrating themes for other tools into this repository at this time, but thanks for offering and for using onedark.vim!

**Comment by jsatk** [comment]
Totally cool. Makes sense. 😄  Thank you.
