### ISSUE TITLE
Setting background to light and then to dark again changes colors

### ISSUE THREAD

**Issue by Filius-Patris** [joshdick/onedark.vim#252]
- [X] I have carefully read and followed the [Installation section of the README](https://github.com/joshdick/onedark.vim#installation)
- [X] I have searched through the [closed issues](https://github.com/joshdick/onedark.vim/issues?q=is%3Aissue+is%3Aclosed) to see if there is an existing solution for my issue

### Terminal Emulator Info

alacritty, default.

### Output From `nvim --version`

```
NVIM v0.5.0-dev+1205-g3f7cd18c4
```

### Issue Description

When run the commands `set background=light` and then `set background=dark` again, the colors change:

Default:
![Screenshot 2021-04-06 at 14 55 42](https://user-images.githubusercontent.com/37048904/113713989-3888ca80-96e8-11eb-80f2-37b765e5763f.png)

After setting background to light and then to dark again:
![Screenshot 2021-04-06 at 14 55 56](https://user-images.githubusercontent.com/37048904/113713960-332b8000-96e8-11eb-8e46-f2d803afde58.png)

Thank you for this colorscheme!!

**Comment by Filius-Patris** [comment]
Appendum: I just found out that running `colorscheme onedark` afterwards reverts everything back to normal again.

Close it if you don't consider it a bug.

**Comment by joshdick** [comment]
Excerpt from `:help background` in Neovim 0.4.4:

```vimhelp
When a color scheme is loaded (the "g:colors_name" variable is set)
setting 'background' will cause the color scheme to be reloaded.  If
the color scheme adjusts to the value of 'background' this will work.
However, if the color scheme sets 'background' itself the effect may
be undone.  First delete the "g:colors_name" variable when needed.
```

`onedark.vim` does include `set background=dark` as its very last line to work around a different issue, which is seemingly what's causing the behavior you're seeing (`if the color scheme sets 'background' itself the effect may be undone.`)

I tried removing `set background=dark` from onedark.vim itself as a test, and this caused Neovim 0.4.4 not to change any colors at all when manually running `set background=light` and `set background=dark` repeatedly. Although this is an odd behavior, because it is easily mitigated by just running `colorscheme onedark` again, I am going to leave the existing `set background=dark` in place and close this issue.

Thanks for the report!
