### ISSUE TITLE
Signify colours

### ISSUE THREAD

**Issue by simonsmith** [joshdick/onedark.vim#28]
Just wondering why these are all set to grey.

Using the `GitGutter` colours looks pretty good.

![screen shot 2016-05-10 at 15 51 26](https://cloud.githubusercontent.com/assets/360703/15150914/12e07298-16c7-11e6-9014-ebd94bf99026.png)

**Comment by simonsmith** [comment]
Oh nice, thanks 👍

**Comment by joshdick** [comment]
You're welcome!

Good catch, this happened because I accidentally stupidly copy-pasted some [lines from a different theme](https://github.com/vim-scripts/vim-colors-pencil/blob/master/colors/pencil.vim#L304-L307) that I found when researching the vim-git-gutter highlight groups -- I should have just read the plugin documentation, heh!
