### ISSUE TITLE
issue with color theme

### ISSUE THREAD

**Issue by uziahmed** [joshdick/onedark.vim#295]
this is really not that much of a big issue but i just wanted to know the images of the onedark theme on the Readme.md are kinda cooler and very similar to the one in atom but i have a much darker and kinda unpleasing color situation here

my init.vim and color situation
![Screenshot_2022-01-04_03-46-14](https://user-images.githubusercontent.com/69237379/147962983-6e4dbf1c-8946-4cd6-81fe-0e0cae10cb05.png)

what i want
![image](https://user-images.githubusercontent.com/69237379/147963088-fb613220-7dd9-4cdc-bf27-b99c4db5d42c.png)

### Terminal Emulator Info
Alacritty 0.9.0

### OS version
OS:Manjaro
kernel:5.13.19-2-MANJARO

### neovim version
neovim version:0.6.0

is there a way to fix it???

**Comment by uziahmed** [comment]
i read the readme.md but found almost nothing that i was looking for

**Comment by joshdick** [comment]
It looks like you're currently using `onedark.vim`'s 256-color mode. To get the colors to look like the README screenshots, you need to enable true/24-bit color mode by adding `set termguicolors` to your configuration before `colorscheme onedark.vim`. If this doesn't work for you, try using the full snippet that appears in Step 2 of the README's installation instructions, instead.

**Comment by uziahmed** [comment]
i mean it kinda worked and fixed the background but the text is still kinda junky and it still doesnt look like the eye soothing one dark
![Screenshot_2022-01-04_04-13-00](https://user-images.githubusercontent.com/69237379/147964981-708f7e6c-c4d5-4cc5-8fde-e1e85b97c6ca.png)

**Comment by joshdick** [comment]
The colors now look correct. I'm not sure what you mean by `the text is still kinda junky` but onedark.vim only styles the colors and nothing else. To change the look of the text, you probably need to experiment with your font / font size / font weight within your alacritty configuration.

The screenshot in the README also utilizes https://github.com/sheerun/vim-polyglot for better syntax highlighting support, but since you're using Neovim you may also want to look into https://github.com/nvim-treesitter/nvim-treesitter.

**Comment by uziahmed** [comment]
i actually meant that the color of the font still kinda doesnt matches the look of the image but anyways thanks for your help and have a great day/night
