### ISSUE TITLE
Different background color in vim vs terminal/tmux

### ISSUE THREAD

**Issue by codemang** [joshdick/onedark.vim#34]
In vim the background is a nice dark gray, but in my terminal it looks like a very dark navy. Have you encountered this issue before?

**Comment by simonsmith** [comment]
I've had this. It's usually around having Vim setup correctly with 256 colors. See if the `16` setting helps:

https://github.com/joshdick/onedark.vim#16-color-mode

**Comment by simonsmith** [comment]
Note that it's supposed to be navy in Vim

**Comment by domingusj** [comment]
I've noticed a similar thing. If I set ```let g:onedark_termcolors=16``` the colors look correct, but comments and syntax highlighting don't look quite right. ```let g:onedark_termcolors=256``` has correct syntax and comment highlighting, but the background is slightly off and the font colors seem a little neon. 256 looks great in MacVim so I assume it's something between my vim and my iTerm2 (beta Build 2.9.20160510). I did download and use the  OneDark.itermcolors files in this repo for my iTerm color profiles. I'd love to figure it out.

**Comment by simonsmith** [comment]
Have you tried using neovim?

**Comment by domingusj** [comment]
That was actually my next move... I will post back if it's better.

**Comment by domingusj** [comment]
Indeed, it looks correct with nvim. Thanks for the suggestion 👍

**Comment by joshdick** [comment]
There are a few things that seem to need clarifying here.

> If I set let g:onedark_termcolors=16 the colors look correct, but comments and syntax highlighting don't look quite right.

@domingusj Can you elaborate? If the colors look correct, comments and syntax highlighting should, too. `g:onedark_termcolors=16` will only look correct in iTerm2 when using `One Dark.itermcolors`, which you did say you've done.

> 256 looks great in MacVim

That's because MacVim is using GUI colors and ignores the `g:onedark_termcolors` setting (the setting *is* called g:onedark_**term**colors after all!)

You can get NeoVim to use the (correct, good-looking) GUI colors **inside the terminal**, regardless of the `g:onedark_termcolors` setting, by following the instructions in the [Neovim section of the README](https://github.com/joshdick/onedark.vim#neovim).

I'm closing this issue since there doesn't appear to be an actual problem, but feel free to keep the dialog going. :)

**Comment by joshdick** [comment]
@codemang What you're seeing is almost certainly because you're using the theme in 256-color mode. Please either use 16 color-mode or NeoVim, as described in the README.

**Comment by domingusj** [comment]
Sure, thanks for all your work on this btw! I really love the scheme!

Here is 16 in iTerm in regular vim (not nvim):

![image](https://cloud.githubusercontent.com/assets/4367223/15409582/953590d6-1dd2-11e6-9b5a-8e93e757b5b5.png)

And here is 256:

![image](https://cloud.githubusercontent.com/assets/4367223/15409600/ad6e6bd2-1dd2-11e6-9979-bb4230c9af1d.png)

You can see the color difference especially on the comments and the slight difference in background color.

**Comment by joshdick** [comment]
@domingusj To me that indicates that something is wrong with the 16-color iTerm preset (or the import of it.) When's the last time you downloaded a fresh copy of it and re-imported it? It has changed a few times during the past couple of weeks.

**Comment by domingusj** [comment]
I'm pretty sure that I re-imported it fairly recently, but I'm not 100% sure. nvim is working great though and I've started moving my stuff over. Thanks again for all your work!

**Comment by joshdick** [comment]
@domingusj Okay, you bet!

**Comment by yarhtut** [comment]
@joshdick 
I have a different background colour in iTerm even I set it to 16.
<img width="1680" alt="screen shot 2017-11-19 at 12 51 48 am" src="https://user-images.githubusercontent.com/8251597/32980011-1561a44c-ccc4-11e7-9277-8a6142bebc57.png">

Thanks

**Comment by yarhtut** [comment]
@joshdick 
Ignore my question. I got it working. Great job on the theme.
<img width="1680" alt="screen shot 2017-11-19 at 1 41 43 am" src="https://user-images.githubusercontent.com/8251597/32980446-48a1b534-cccb-11e7-9794-009a9372d1cb.png">

**Comment by yuhuanq** [comment]
@yarhtut Have this same dark grayish bg. What did you change to get it working?

**Comment by hereisfun** [comment]
same issue like @joshdick 
here is my solution, maybe useful for somebody(MacOS, iterm2)

after setting `tmux -2`, `xterm-256color`, and `$TERM`, things doesn't get better.

and if I use `let g:onedark_termcolors=16`, my comments turn white like this:
![image](https://user-images.githubusercontent.com/20593467/39305763-c1f0805e-4990-11e8-9d99-11fdee6662cd.png)

At last I found the reason is, I used an onedark theme for iterm from [nathanbuchar/atom-one-dark-terminal](https://github.com/nathanbuchar/atom-one-dark-terminal), with doesn't work well with 16bit onedark.vim!

So I switch to `term/One Dark.itermcolors` from this project, setting `let g:onedark_termcolors=16`, and finally everything is perfect❤️

**Comment by reidcooper** [comment]
How can i determine the color scheme definition for colors when it looks like this? I actually like it...

![ad6e6bd2-1dd2-11e6-9979-bb4230c9af1d](https://user-images.githubusercontent.com/6921277/46096793-1f554980-c18e-11e8-9b72-dad903c2c121.png)

**Comment by joshdick** [comment]
@reidcooper That is the 8-bit/256 color palette, whose colors are defined as the `cterm` values in [`autoload/onedark.vim`](https://github.com/joshdick/onedark.vim/blob/master/autoload/onedark.vim).

To get hex equivalents to those colors, you'll have to look up the aforementioned `cterm` color values in a table like [this one](https://jonasjacek.github.io/colors/).

I hope that helps!

**Comment by reidcooper** [comment]
@joshdick Thanks! That makes sense. As for the attributes `gui`, `cterm`, and `cterm16`, are those the 3 different possible color values that can be displayed for that one override?

When are any of the 3 chosen? New to vim.

**Comment by joshdick** [comment]
@reidcooper You’re welcome!

For any given color definition, `gui` is what is used in true (24-bit) color mode, `cterm` is what is used in 256-color mode, and `cterm16` is used in 16-color mode, except in this case, the actual 16 colors are defined by your terminal emulator configuration and nubmered 0-15, and the theme can only pick from those predefined colors.

So, every color definition is actually three definitions since each color needs to work in three modes.

Your configuration is what determines which mode is used. The [README](
https://github.com/joshdick/onedark.vim) goes into a lot of detail about that.
