### ISSUE TITLE
colors not showing as the example

### ISSUE THREAD

**Issue by bronzdoc** [joshdick/onedark.vim#4]
I found that the colorscheme is not showing as the example found here http://vimcolors.com/354/onedark/dark the color scheme is actually looking like this http://i.imgur.com/Q5wQbaO.png?1
 
i'm using neovim and starting it with <code>NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim</code> wich enables true colors.

**Comment by joshdick** [comment]
I'm not sure how the example was getting generated, since there were colors that appeared for syntax groups where the theme had no colors defined.

I've just pushed some changes that get the example code to look closer to how it does using the actual One Dark theme inside Atom.

Thanks for the report!

**Comment by bronzdoc** [comment]
Thanks for the clarification and the awesome colorscheme =)

**Comment by joshdick** [comment]
You bet, glad you like it!
