### ISSUE TITLE
Cant highlight ColorColumn

### ISSUE THREAD

**Issue by junkmechanic** [joshdick/onedark.vim#55]
Hi,

Beautiful theme.
I am using it with neovim inside tmux. I set my colorcolumn as well. But I cant see it highlight-ed to `cursor_grey`. `hitest` doesnt show any color for it as well.
I have tried using a different color `hi ColorColumn ctermbg=black` for example but it doesnt seem to work.

Any pointers?

**Comment by joshdick** [comment]
My guess is that you're running the theme and neovim in true-color mode, which would explain why using `ctermbg` has no effect. If so, you'll need to use `guibg` instead of `ctermbg` (for example, `hi ColorColumn guibg=black`).

If I guessed wrong, just let me know and we'll continue troubleshooting. 😄

**Comment by junkmechanic** [comment]
Spot on. Thanks for the help.

Cheers!
