### ISSUE TITLE
Highlight Group 'IncSearch' interferes with SearchParty

### ISSUE THREAD

**Issue by junkmechanic** [joshdick/onedark.vim#57]
Hi @joshdick ,

I use SearchParty and one of its features is to use IncSearch and highlight the occurrence under the cursor using the inverted colorscheme of the Syntax group the word belongs to.

This gets overridden when hl-IncSearch is explicitly defined, as is the case here. If you dont see this as a deal breaker, I would request removing (or temporarily commenting it out).

Alternatively, you could use a flag for the user to set/reset this hl group.

Cheers

**Comment by joshdick** [comment]
I haven't used SearchParty, but I believe the colorscheme's current behavior for `IncSearch` should stay as is. I'm not familiar with exactly how SearchParty uses that highlight group, but shouldn't it be the plugin's responsibility to do any special handling of a highlight group appropriately/as it needs to?

To work around this issue, is there any reason you can't put `hi clear IncSearch` somewhere in your `.vimrc` to override onedark's styling?

Since I don't [yet] plan on making any specific changes related to this issue, I'm going to close it, but I'm happy to continue the discussion here. :)

**Comment by junkmechanic** [comment]
Makes sense. I will heed your advice.
Cheers
