### ISSUE TITLE
Include onedark to vim-airline-themes

### ISSUE THREAD

**Issue by nocode99** [joshdick/onedark.vim#80]
Hi,

I was going to submit a PR to https://github.com/vim-airline/vim-airline-themes to include your onedark airline autoload but wasn't sure if that is something you want to do instead.

Essentially, it allows people to use the one plugin to use other themes.

Thanks!
Byron

**Comment by joshdick** [comment]
Byron,

This is a great idea in theory but not in practice, at least not right now, since onedark.vim's airline theme depends on onedark.vim itself for its colors and is thus not usable on its own/without also using onedark.vim. This is not the case for all of the themes in that repository (they're all standalone and will work independently of which Vim colorscheme is used.)

I would rather not duplicate the color values from onedark.vim itself into the airline theme in order to make it not depend on onedark.vim, so unless we introduce a build process for theme that substitutes colors into both places (something like how [base16-vim](https://github.com/chriskempson/base16-vim)) is built, I am going to hold off on this idea for now and close the issue.

Thanks for the suggestion!

**Comment by joshdick** [comment]
(To clarify, the colors in the lightline colorscheme are currently hardcoded, which is already not great, and I don't want to make the problem worse by hardcoding colors in three places.)

**Comment by joshdick** [comment]
I thought more about this issue and decided to implement a build system after all (#81), which let me submit a PR to vim-airline-themes as you originally suggested:

https://github.com/vim-airline/vim-airline-themes/pull/70

Thanks again for the suggestion!
