### ISSUE TITLE
Could it be possible to override the airline settings?

### ISSUE THREAD

**Issue by simonsmith** [joshdick/onedark.vim#89]
I've been tweaking my `statusline` to be more minimal and as a consequence I wanted the non-focused status lines to be super simple and remove the grey background color:

![screen shot 2017-02-25 at 16 09 49](https://cloud.githubusercontent.com/assets/360703/23332637/00483f1a-fb75-11e6-819c-ca158820e2ec.png)

![screen shot 2017-02-25 at 16 10 11](https://cloud.githubusercontent.com/assets/360703/23332639/0586b416-fb75-11e6-8f98-74a0c4a4fa02.png)

I managed to do it by tweaking the airline theme but was wondering if it's a huge hassle to allow that as an override? If not I don't mind just keeping a fork up to date as it's a minimal change.

Another question is should we keep that grey background there at all, considering the active window does not have one?

Here's my more minimal setup:

![screen shot 2017-02-25 at 12 17 25](https://cloud.githubusercontent.com/assets/360703/23332671/725a0c64-fb75-11e6-9a09-77097403bb62.png)

I think it complements it well to blend with the background colour.

EDIT: I've noticed my minimal approach is perhaps less clear when it comes to horizontal splits so maybe some kind of border is needed.

**Comment by joshdick** [comment]
As you figured out, I seem to remember someone filing an issue relating to inactive splits being hard to see without that explicit grey background color, but the issue was likely filed against the (now deleted) airline-onedark repo since I can't find that issue associated with this repo.

Not sure what you have in mind for a border. Even without lightline.vim/vim-airline, I forget how the default `VertSplit`, `StatusLine`, and `StatusLineNC` highlight groups all look/play together as they currently exist the theme, since I use lightline.vim and never see them, ha!

**Comment by simonsmith** [comment]
Ha okay no problem. I might just leave this as customisation for me
