### ISSUE TITLE
Search and IncSearch

### ISSUE THREAD

**Issue by muffinmad** [joshdick/onedark.vim#94]
Since `Search` and `IncSearch` have same highlight options it's very hard to know which text is going to be replaced while doing substitue with `:s///c`. 
It would be nice if the background of the `Search` would be darker than `IncSearch`.

**Comment by joshdick** [comment]
Are you using 16-, 256- or 24-bit color?

**Comment by muffinmad** [comment]
I'm using 24-bit color.
```
:hi Search
Search         xxx term=reverse ctermfg=235 ctermbg=180 guifg=#282C34 guibg=#E5C07B

:hi IncSearch
IncSearch      xxx term=reverse ctermfg=235 ctermbg=180 guifg=#282C34 guibg=#E5C07B
```
Judging by colorscheme file both Search and IncSearch recieves same highlight options: `{ "fg": s:black, "bg": s:yellow }`

**Comment by joshdick** [comment]
I originally asked the question about color since I initially wasn't sure if this was a question about background color (especially concerning the very limited colors available in 16-color mode) but your clarification about `Search` and `IncSearch` showed me what you were after.

I've changed the `IncSearch` styling to be visually different, I hope that helps this issue!
