### ISSUE TITLE
comments are highlighted

### ISSUE THREAD

**Issue by vutran** [joshdick/onedark.vim#97]
For some reason, all my comments are highlighted like so (regardless of language), see example below:

<img width="397" alt="screenshot 2017-05-06 14 59 44" src="https://cloud.githubusercontent.com/assets/1088312/25776191/c295ef30-326c-11e7-97a6-4d5f1f4d73e4.png">

I'm currently using iTerm with the provided `.itermcolors` with and vim color.

**Comment by joshdick** [comment]
This is happening because you have italics enabled, but some combination of your iTerm2 reported terminal type and terminfo database is causing italics to be displayed incorrectly.

Two solutions are:

1) (Hopefully) fix italics by doing the following:
    1) In iTerm2 preferences, on the "Terminal" tab, for the "Report Terminal Type:" setting, select "xtern-256color" if it's not already selected
    2) Create a file somewhere on disk with the following contents:
    ```
    xterm-256color|xterm with 256 colors and italic,
      sitm=\E[3m, ritm=\E[23m,
      use=xterm-256color,
    ```
    3) In a shell, run `tic path/to/the/file/you/just/made`
    4) Quit and restart iTerm2
    5) Vim should now display italics properly

or,

2) Disable italics by removing the `g:onedark_terminal_italics` setting for `onedark.vim` from your Vim configuration.

**Comment by vutran** [comment]
> Disable italics by removing the g:onedark_terminal_italics setting for onedark.vim from your Vim configuration.

This did it. Much appreciated for the help.

**Comment by joshdick** [comment]
You're welcome!
